### ISSUE TITLE
Doesn't work with mongoid 6

### ISSUE THREAD

**Issue by michalvalasek** [berniechiu/mongoid_enum_mapper#1]
Is there a reason why the mongoid dependency must be pinned to version 4?

```
Bundler could not find compatible versions for gem "mongoid":
  In snapshot (Gemfile.lock):
    mongoid (= 6.2.1)

  In Gemfile:
    mongoid_enum_mapper was resolved to 0.1.0, which depends on
      mongoid (~> 4.0.2)
```

**Comment by berniechiu** [comment]
I haven't fully tested on `mongoid 6` yet, but I'll take that into consideration

And welcome any PR here if you've tested on 6 already~

**Comment by berniechiu** [comment]
Added support for Mongoid 6, thx for suggestion~

**Comment by michalvalasek** [comment]
Great thanks @berniechiu for this update!
